### ISSUE TITLE
Chapter 1: "The "@angular/compiler-cli" package was not properly installed" error

### ISSUE THREAD

**Issue by hkarakose** [PacktPublishing/Learning-Ionic-Second-Edition#1]
When executing `ng serve` for Chapter 1/gliphy application I get `The "@angular/compiler-cli" package was not properly installed.` error.

```
Halils-MacBook-Pro:giphy-app halil$ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.2
node: 7.10.0
os: darwin x64
@angular/common: 2.1.2
@angular/compiler: 2.1.2
@angular/core: 2.1.2
@angular/forms: 2.1.2
@angular/http: 2.1.2
@angular/platform-browser: 2.1.2
@angular/platform-browser-dynamic: 2.1.2
@angular/router: 3.1.2
@angular/cli: 1.1.2
@angular/compiler-cli: 2.1.0
Halils-MacBook-Pro:giphy-app halil$ ng serve
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/halil/Projects/user_projects/book source codes/Learning-Ionic-Second-Edition/Chapter01/giphy-app/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/halil/Projects/user_projects/book source codes/Learning-Ionic-Second-Edition/Chapter01/giphy-app/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

**Comment by sonam-packt** [comment]
Please reopen if the issue persist.
